# Generated by Django 5.2.7 on 2025-11-05 02:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='security_number',
            field=models.CharField(default=users.models.generate_security_number, max_length=20, unique=True),
        ),
    ]
