# Generated by Django 4.2.7 on 2025-11-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('Password', 'Password'), ('Face Recognition', 'Face Recognition'), ('Smart Card', 'Smart Card'), ('Biometric', 'Biometric'), ('Registration', 'Registration'), ('Admin Action', 'Admin Action'), ('Logout', 'Logout'), ('System', 'System')], max_length=20)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('geolocation', models.CharField(blank=True, max_length=100)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('attempt_number', models.IntegerField(default=1)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('active_users', models.IntegerField()),
                ('request_count', models.IntegerField()),
                ('average_response_time', models.FloatField()),
                ('database_status', models.BooleanField(default=True)),
                ('face_recognition_status', models.BooleanField(default=True)),
                ('storage_status', models.BooleanField(default=True)),
                ('failed_logins', models.IntegerField(default=0)),
                ('security_alerts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health Records',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['timestamp'], name='identity_ve_timesta_745e5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_enrolled', models.BooleanField(default=False)),
                ('face_enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('face_encoding_1', models.TextField(blank=True, null=True)),
                ('face_encoding_2', models.TextField(blank=True, null=True)),
                ('face_encoding_count', models.IntegerField(default=0)),
                ('face_encoding_version', models.CharField(default='2.0', max_length=10)),
                ('security_clearance', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='RESTRICTED', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('service_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_face_update', models.DateTimeField(blank=True, null=True)),
                ('enrollment_quality_score', models.FloatField(blank=True, null=True)),
                ('last_verification', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['face_enrolled'], name='identity_ve_face_en_1b1252_idx'), models.Index(fields=['security_clearance'], name='identity_ve_securit_777d36_idx'), models.Index(fields=['service_number'], name='identity_ve_service_ffccf7_idx'), models.Index(fields=['last_verification'], name='identity_ve_last_ve_a5f9ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'indexes': [models.Index(fields=['key'], name='identity_ve_key_7f4811_idx'), models.Index(fields=['is_public'], name='identity_ve_is_publ_bce5c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(choices=[('SUSPICIOUS_LOGIN', 'Suspicious Login'), ('MULTIPLE_FAILURES', 'Multiple Failures'), ('UNUSUAL_LOCATION', 'Unusual Location'), ('SYSTEM_SECURITY', 'System Security'), ('BIOMETRIC_ISSUE', 'Biometric Issue'), ('DATA_BREACH', 'Data Breach'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=20)),
                ('alert_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='identity_verification.accesslog')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_level'], name='identity_ve_alert_l_964050_idx'), models.Index(fields=['alert_type'], name='identity_ve_alert_t_e8fd0c_idx'), models.Index(fields=['is_resolved'], name='identity_ve_is_reso_6e9385_idx'), models.Index(fields=['created_at'], name='identity_ve_created_2c2da2_idx'), models.Index(fields=['acknowledged'], name='identity_ve_acknowl_8ad3c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEncodingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField()),
                ('encoding_version', models.CharField(max_length=10)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(default='Update', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_encodings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Encoding Archive',
                'verbose_name_plural': 'Face Encoding Archives',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['user', 'archived_at'], name='identity_ve_user_id_7f97b8_idx'), models.Index(fields=['archived_at'], name='identity_ve_archive_4865b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp'], name='identity_ve_timesta_92d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'timestamp'], name='identity_ve_user_id_f04014_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['login_method', 'status'], name='identity_ve_login_m_fcfca2_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='identity_ve_ip_addr_3e5833_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['is_suspicious'], name='identity_ve_is_susp_89101f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['confidence_score'], name='identity_ve_confide_7cdb70_idx'),
        ),
    ]
