# Generated by Django 5.2.7 on 2025-11-06 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=200)),
                ('service_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('security_clearance', models.CharField(choices=[('TOP SECRET', 'Top Secret'), ('SECRET', 'Secret'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='RESTRICTED', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Air Force Zimbabwe Identity System', max_length=200)),
                ('max_login_attempts', models.IntegerField(default=3)),
                ('session_timeout', models.IntegerField(default=30)),
                ('face_match_threshold', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='IDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('id_type', models.CharField(choices=[('MILITARY_ID', 'Military ID'), ('ACCESS_CARD', 'Access Card'), ('VISITOR_PASS', 'Visitor Pass')], default='MILITARY_ID', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_records', to='identity_verification.person')),
            ],
            options={
                'verbose_name': 'ID Record',
                'verbose_name_plural': 'ID Records',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_ATTEMPT', 'Login Attempt'), ('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_DENIED', 'Access Denied'), ('ID_ISSUED', 'ID Issued'), ('ID_REVOKED', 'ID Revoked'), ('FACE_VERIFICATION_SUCCESS', 'Face Verification Success'), ('FACE_VERIFICATION_FAILED', 'Face Verification Failed')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='identity_verification.person')),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
            },
        ),
    ]
